name: daily
on:
  schedule:
    - cron: '0 17 * * *'
  workflow_dispatch:

jobs:
  doit:
    name: 'do it'
    runs-on: ubuntu-latest
    env:
      BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
      CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: 1.15.x
      - name: Parse current date
        id: parse_date
        run: |-
          echo "::set-output name=week::$(/bin/date -u "+%V")"
      - uses: actions/cache@v2
        id: cache_flavors
        with:
          path: newcity.json
          key: flavors-${{ runner.os }}-${{ steps.parse_date.outputs.week }}
      - name: Run
        run: |-
          go run . -channel_id=$CHANNEL_ID -only_originals -cache
