name: daily
on:
  schedule:
    - cron: '0 17 * * *'
  workflow_dispatch:

jobs:
  doit:
    name: 'do it'
    runs-on: ubuntu-latest
    env:
      BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
      CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: 1.15.x
      - name: Parse dates
        id: parse_dates
        run: |-
          echo "::set-output name=today_week::$(/bin/date -u "+%V")"
          echo "::set-output name=today_day::$(/bin/date -u "+%u")"
          echo "::set-output name=yesterday_week::$(/bin/date --date="yesterday" -u "+%V")"
          echo "::set-output name=yesterday_day::$(/bin/date --date="yesterday" -u "+%u")"
      - name: Handle today's cache file
        uses: actions/cache@v2
        id: cache_today_flavors
        with:
          path: newcity.json
          key: flavors-${{ steps.parse_dates.outputs.today_week }}-${{ steps.parse_dates.outputs.today_day }}
      - name: Handle yesterday's cache file
        uses: actions/cache@v2
        id: get_yesterday_flavors
        with:
          path: newcity.json
          key: flavors-${{ steps.parse_dates.outputs.yesterday_week }}-${{ steps.parse_dates.outputs.yesterday_day }}
      - name: Run
        run: |-
          if [ "${{ steps.parse_dates.outputs.today_week }}" == "${{ steps.parse_dates.outputs.yesterday_week }}" ]; then
            go run . -channel_id=$CHANNEL_ID -only_originals -cache -dry_run
          else
            go run . -channel_id=$CHANNEL_ID -only_originals -dry_run
          fi
