name: daily
on:
  schedule:
    - cron: '0 17 * * *'
  workflow_dispatch:

jobs:
  doit:
    name: 'do it'
    runs-on: ubuntu-latest
    env:
      BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
      CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: 1.15.x
      - name: Parse dates
        id: parse_dates
        run: |
          echo "::set-output name=today_week::$(/bin/date -u "+%V")"
          echo "::set-output name=today_day::$(/bin/date -u "+%u")"
          echo "::set-output name=yesterday_week::$(/bin/date --date="yesterday" -u "+%V")"
          echo "::set-output name=yesterday_day::$(/bin/date --date="yesterday" -u "+%u")"
      # - name: Extract Cache
      #   id: extract_cache
      #   if: ${{ steps.parse_dates.outputs.today_week }} == ${{ steps.parse_dates.outputs.yesterday_week }}
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     go run ./cmd/extract_cache \
      #       -key=flavors-${{ steps.parse_dates.outputs.yesterday_week }}-${{ steps.parse_dates.outputs.yesterday_day }} \
      #       -path=newcity.json
      - name: New City
        id: newcity
        run: |
          go run ./cmd/newcity \
            -channel_id=$CHANNEL_ID \
            -only_originals \
            -cache
      - uses: actions/upload-artifact@v2
        with:
          name: flavors-${{ steps.parse_dates.outputs.today_week }}-${{ steps.parse_dates.outputs.today_day }}
          path: |
            newcity.json
